# Downloads + unpacks a sherpa-onnx piper voice into DEST (cached). Never fails: the test skips if absent.
if(EXISTS "${DEST}/tokens.txt")
  return()
endif()
file(MAKE_DIRECTORY "${DEST}")
set(_f "${DEST}/voice.tar.bz2")
file(DOWNLOAD "${URL}" "${_f}" STATUS _st TLS_VERIFY ON)
list(GET _st 0 _rc)
if(NOT _rc EQUAL 0)
  message(WARNING "voice download failed: ${_st}")
  file(REMOVE "${_f}")
  return()
endif()
file(ARCHIVE_EXTRACT INPUT "${_f}" DESTINATION "${DEST}/_x")
file(GLOB _sub LIST_DIRECTORIES true "${DEST}/_x/*")
list(GET _sub 0 _top)
file(GLOB _items "${_top}/*")
foreach(i ${_items})
  file(COPY "${i}" DESTINATION "${DEST}")
endforeach()
file(REMOVE_RECURSE "${DEST}/_x")
file(REMOVE "${_f}")
