# Assembles ${DATA}/models for engine tests. Never fails (tests skip parts that are missing).
set(M "${DATA}/models")
file(MAKE_DIRECTORY "${M}/vad" "${M}/tts/us" "${M}/whisper")
if(NOT EXISTS "${M}/vad/silero_vad.onnx")
  file(DOWNLOAD "https://raw.githubusercontent.com/snakers4/silero-vad/v6.2/src/silero_vad/data/silero_vad.onnx"
       "${M}/vad/silero_vad.onnx" STATUS st TLS_VERIFY ON)
  list(GET st 0 rc)
  if(NOT rc EQUAL 0)
    file(REMOVE "${M}/vad/silero_vad.onnx")
    message(WARNING "silero download failed: ${st}")
  endif()
endif()
execute_process(COMMAND ${CMAKE_COMMAND} -DURL=${VOICE_URL} -DDEST=${VOICE} -P ${VOICE_SCRIPT})
if(EXISTS "${VOICE}/tokens.txt" AND NOT EXISTS "${M}/tts/us/tokens.txt")
  file(GLOB _onx "${VOICE}/*.onnx")
  list(GET _onx 0 _o)
  file(COPY "${_o}" DESTINATION "${M}/tts/us")
  get_filename_component(_on "${_o}" NAME)
  file(RENAME "${M}/tts/us/${_on}" "${M}/tts/us/model.onnx")
  file(COPY "${VOICE}/tokens.txt" "${VOICE}/espeak-ng-data" DESTINATION "${M}/tts/us")
endif()
if(EXISTS "${WHISPER_TEST_MODEL}" AND NOT EXISTS "${M}/whisper/for-tests-ggml-tiny.en.bin")
  file(COPY "${WHISPER_TEST_MODEL}" DESTINATION "${M}/whisper")
endif()
if(EXISTS "${CMUDICT}")
  file(COPY "${CMUDICT}" DESTINATION "${M}/cmudict")
endif()
